//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// 此源代码由 xsd 自动生成, Version=4.0.30319.17929。
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class QueryOrderStatusInfo {
    
    private string orderNumberField;
    
    private int orderStatusCodeField;
    
    private QueryOrderStatusInfoOrderStatusName orderStatusNameField;
    
    private string sellerIDField;
    
    private QueryOrderStatusInfoOrderDownloaded orderDownloadedField;
    
    private int salesChannelField;
    
    private bool salesChannelFieldSpecified;
    
    private int fulfillmentOptionField;
    
    private bool fulfillmentOptionFieldSpecified;
    
    /// <summary>
    /// 订单号
    /// </summary>
    public string OrderNumber {
        get {
            return this.orderNumberField;
        }
        set {
            this.orderNumberField = value;
        }
    }
    
    /// <summary>
    /// 订单状态（0:Unshipped未发货; 1:PartiallyShipped部分发货;  2:Shipped已发货;  3:Invoiced已生成发票  4:Void）
    /// </summary>
    public int OrderStatusCode {
        get {
            return this.orderStatusCodeField;
        }
        set {
            this.orderStatusCodeField = value;
        }
    }
    
    /// <summary>
    /// 订单状态描述（0:Unshipped未发货; 1:PartiallyShipped部分发货;  2:Shipped已发货;  3:Invoiced已生成发票  4:Void）
    /// </summary>
    public QueryOrderStatusInfoOrderStatusName OrderStatusName {
        get {
            return this.orderStatusNameField;
        }
        set {
            this.orderStatusNameField = value;
        }
    }
    
    /// <remarks/>
    public string SellerID {
        get {
            return this.sellerIDField;
        }
        set {
            this.sellerIDField = value;
        }
    }
    
    /// <remarks/>
    public QueryOrderStatusInfoOrderDownloaded OrderDownloaded {
        get {
            return this.orderDownloadedField;
        }
        set {
            this.orderDownloadedField = value;
        }
    }
    
    /// <remarks/>
    public int SalesChannel {
        get {
            return this.salesChannelField;
        }
        set {
            this.salesChannelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SalesChannelSpecified {
        get {
            return this.salesChannelFieldSpecified;
        }
        set {
            this.salesChannelFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int FulfillmentOption {
        get {
            return this.fulfillmentOptionField;
        }
        set {
            this.fulfillmentOptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FulfillmentOptionSpecified {
        get {
            return this.fulfillmentOptionFieldSpecified;
        }
        set {
            this.fulfillmentOptionFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum QueryOrderStatusInfoOrderStatusName {
    
    /// <remarks/>
    Unshipped,
    
    /// <remarks/>
    PartiallyShipped,
    
    /// <remarks/>
    Shipped,
    
    /// <remarks/>
    Invoiced,
    
    /// <remarks/>
    Void,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum QueryOrderStatusInfoOrderDownloaded {
    
    /// <remarks/>
    @true,
    
    /// <remarks/>
    @false,
}
