//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// 此源代码由 xsd 自动生成, Version=4.0.30319.17929。
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class UpdateOrderStatusInfo {
    
    private UpdateOrderStatusInfoIsSuccess isSuccessField;
    
    private UpdateOrderStatusInfoPackageProcessingSummary packageProcessingSummaryField;
    
    private UpdateOrderStatusInfoResult resultField;
    
    /// <remarks/>
    public UpdateOrderStatusInfoIsSuccess IsSuccess {
        get {
            return this.isSuccessField;
        }
        set {
            this.isSuccessField = value;
        }
    }
    
    /// <remarks/>
    public UpdateOrderStatusInfoPackageProcessingSummary PackageProcessingSummary {
        get {
            return this.packageProcessingSummaryField;
        }
        set {
            this.packageProcessingSummaryField = value;
        }
    }
    
    /// <remarks/>
    public UpdateOrderStatusInfoResult Result {
        get {
            return this.resultField;
        }
        set {
            this.resultField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum UpdateOrderStatusInfoIsSuccess {
    
    /// <remarks/>
    @true,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class UpdateOrderStatusInfoPackageProcessingSummary {
    
    private string totalPackageCountField;
    
    private string successCountField;
    
    private string failCountField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string TotalPackageCount {
        get {
            return this.totalPackageCountField;
        }
        set {
            this.totalPackageCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string SuccessCount {
        get {
            return this.successCountField;
        }
        set {
            this.successCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string FailCount {
        get {
            return this.failCountField;
        }
        set {
            this.failCountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class UpdateOrderStatusInfoResult {
    
    private string orderNumberField;
    
    private string sellerIDField;
    
    private UpdateOrderStatusInfoResultOrderStatus orderStatusField;
    
    private UpdateOrderStatusInfoResultShipment shipmentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string OrderNumber {
        get {
            return this.orderNumberField;
        }
        set {
            this.orderNumberField = value;
        }
    }
    
    /// <remarks/>
    public string SellerID {
        get {
            return this.sellerIDField;
        }
        set {
            this.sellerIDField = value;
        }
    }
    
    /// <remarks/>
    public UpdateOrderStatusInfoResultOrderStatus OrderStatus {
        get {
            return this.orderStatusField;
        }
        set {
            this.orderStatusField = value;
        }
    }
    
    /// <remarks/>
    public UpdateOrderStatusInfoResultShipment Shipment {
        get {
            return this.shipmentField;
        }
        set {
            this.shipmentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum UpdateOrderStatusInfoResultOrderStatus {
    
    /// <remarks/>
    Shipped,
    
    /// <remarks/>
    PartiallyShipped,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class UpdateOrderStatusInfoResultShipment {
    
    private UpdateOrderStatusInfoResultShipmentPackage[] packageListField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Package", IsNullable=false)]
    public UpdateOrderStatusInfoResultShipmentPackage[] PackageList {
        get {
            return this.packageListField;
        }
        set {
            this.packageListField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class UpdateOrderStatusInfoResultShipmentPackage {
    
    private string trackingNumberField;
    
    private string shipDateField;
    
    private UpdateOrderStatusInfoResultShipmentPackageProcessStatus processStatusField;
    
    private string processResultField;
    
    private UpdateOrderStatusInfoResultShipmentPackageItemDes[] itemListField;
    
    /// <remarks/>
    public string TrackingNumber {
        get {
            return this.trackingNumberField;
        }
        set {
            this.trackingNumberField = value;
        }
    }
    
    /// <remarks/>
    public string ShipDate {
        get {
            return this.shipDateField;
        }
        set {
            this.shipDateField = value;
        }
    }
    
    /// <remarks/>
    public UpdateOrderStatusInfoResultShipmentPackageProcessStatus ProcessStatus {
        get {
            return this.processStatusField;
        }
        set {
            this.processStatusField = value;
        }
    }
    
    /// <remarks/>
    public string ProcessResult {
        get {
            return this.processResultField;
        }
        set {
            this.processResultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ItemDes", IsNullable=false)]
    public UpdateOrderStatusInfoResultShipmentPackageItemDes[] ItemList {
        get {
            return this.itemListField;
        }
        set {
            this.itemListField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum UpdateOrderStatusInfoResultShipmentPackageProcessStatus {
    
    /// <remarks/>
    @true,
    
    /// <remarks/>
    @false,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class UpdateOrderStatusInfoResultShipmentPackageItemDes {
    
    private string sellerPartNumberField;
    
    private string neweggItemNumberField;
    
    private string shippedQtyField;
    
    /// <remarks/>
    public string SellerPartNumber {
        get {
            return this.sellerPartNumberField;
        }
        set {
            this.sellerPartNumberField = value;
        }
    }
    
    /// <remarks/>
    public string NeweggItemNumber {
        get {
            return this.neweggItemNumberField;
        }
        set {
            this.neweggItemNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string ShippedQty {
        get {
            return this.shippedQtyField;
        }
        set {
            this.shippedQtyField = value;
        }
    }
}
