//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// 此源代码由 xsd 自动生成, Version=4.0.30319.17929。
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ShipmentEgg {
    
    private ShipmentHeader headerField;
    
    private ShipmentPackageList packageListField;
    
    /// <remarks/>
    public ShipmentHeader Header {
        get {
            return this.headerField;
        }
        set {
            this.headerField = value;
        }
    }
    
    /// <remarks/>
    public ShipmentPackageList PackageList {
        get {
            return this.packageListField;
        }
        set {
            this.packageListField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ShipmentHeader {
    
    private string sellerIDField;
    
    private int sONumberField;
    
    /// <remarks/>
    public string SellerID {
        get {
            return this.sellerIDField;
        }
        set {
            this.sellerIDField = value;
        }
    }
    
    /// <remarks/>
    public int SONumber {
        get {
            return this.sONumberField;
        }
        set {
            this.sONumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ShipmentPackageList {
    
    private ShipmentPackageListPackage[] packageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Package")]
    public ShipmentPackageListPackage[] Package {
        get {
            return this.packageField;
        }
        set {
            this.packageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ShipmentPackageListPackage {
    
    private string trackingNumberField;
    
    private string shipCarrierField;
    
    private string shipServiceField;
    
    private ShipmentPackageListPackageItem[] itemListField;
    
    /// <remarks/>
    public string TrackingNumber {
        get {
            return this.trackingNumberField;
        }
        set {
            this.trackingNumberField = value;
        }
    }
    
    /// <remarks/>
    public string ShipCarrier {
        get {
            return this.shipCarrierField;
        }
        set {
            this.shipCarrierField = value;
        }
    }
    
    /// <remarks/>
    public string ShipService {
        get {
            return this.shipServiceField;
        }
        set {
            this.shipServiceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Item", IsNullable=false)]
    public ShipmentPackageListPackageItem[] ItemList {
        get {
            return this.itemListField;
        }
        set {
            this.itemListField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ShipmentPackageListPackageItem {
    
    private string sellerPartNumberField;
    
    private string neweggItemNumberField;
    
    private int shippedQtyField;
    
    /// <remarks/>
    public string SellerPartNumber {
        get {
            return this.sellerPartNumberField;
        }
        set {
            this.sellerPartNumberField = value;
        }
    }
    
    /// <remarks/>
    public string NeweggItemNumber {
        get {
            return this.neweggItemNumberField;
        }
        set {
            this.neweggItemNumberField = value;
        }
    }
    
    /// <remarks/>
    public int ShippedQty {
        get {
            return this.shippedQtyField;
        }
        set {
            this.shippedQtyField = value;
        }
    }
}
